### ISSUE TITLE
Noto Sans font files missing

### ISSUE THREAD

**Issue by kulame** [DecliningLotus/fontsource#353]
**Describe the bug**
i try to build a project with fontsource. but it tell me 
./node_modules/@fontsource/noto-sans-jp/japanese-400.css
Error: Can't resolve './files/noto-sans-jp-japanese-400-normal.woff2' in '/srv/demo/umami/node_modules/@fontsource/noto-sans-jp'
    at runMicrotasks (<anonymous>)

**To Reproduce**
```shell
git clone https://github.com/mikecao/umami.git
cd umami
npm i
npm run build
```

**Expected behavior**
build pass

**Screenshots**

**Additional context**
    "@fontsource/inter": "^4.5.0",
    "@fontsource/noto-sans-jp": "^4.5.0",
    "@fontsource/noto-sans-sc": "^4.5.0",
    "@fontsource/noto-sans-tc": "^4.5.0",

**Comment by kulame** [comment]
i found the file noto-sans-jp-japanese-400-normal.woff2  not exist on fontsource

**Comment by ahrbil** [comment]
Hello @kulame, I have the same issue with the Noto Sans KR version
I updated to @fontsource/noto-sans-kr v4.5.1 but I still have the same error "Can't resolve './files/noto-sans-kr-korean-100-normal.woff2' "

**Comment by ayuhito** [comment]
Google seems to have pushed an update to their CSS API (I have a guess it's to do with the whole Noto Fonts rework) which seems to have affected us downstream. I'll need time to investigate this a bit more since I am currently travelling but should finally get back home in a couple of days.

I suggest **downgrading to 4.5.0 (pinned)** for the time being, which seems to be a working version. You are likely downloading 4.5.1 which was after Google pushing their Noto update. 

For other developers, let me know if any of the non-Noto fonts are affected since I'm not sure if the scope is larger than that.

I'll pin this issue for the time being.

**Comment by ayuhito** [comment]
Oh no. This is way worse than I thought and can't be fixed by me. I'll be making an issue at Google Fonts to address this since it's a breaking change they have made with their APIs.

**Comment by ahrbil** [comment]
Thank you @DecliningLotus downgrading to the 4.5.0 version fixed it for me.

**Comment by BrainEno** [comment]
`error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[3].oneOf[5].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[3].oneOf[5].use[2]!./node_modules/@fontsource/noto-sans-sc/chinese-simplified-400.css
Error: Can't resolve './files/noto-sans-sc-chinese-simplified-400-normal.woff2' in 'H:\seoblog\frontend\node_modules\@fontsource\noto-sans-sc' `
Having the same problem with nextjs version 11.1.2

**Comment by ibqn** [comment]
Also, hit by this one with noto-sans-kr font

Error: Can't resolve './files/noto-sans-kr-0-400-normal.woff2' in '/vercel/path0/node_modules/@fontsource/noto-sans-kr'
20:08:26.650      > Build error occurred
20:08:26.650      Error: > Build failed because of webpack errors
20:08:26.650          at /vercel/path0/node_modules/next/dist/build/index.js:397:19
20:08:26.651          at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
20:08:26.651          at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:77:25)
20:08:26.704      error Command failed with exit code 1.

**Comment by ayuhito** [comment]
Hopefully, this fix should address this issue. It will take a few hours for the entire repository to rebuild itself and publish onto NPM, however.

**Comment by ayuhito** [comment]
```
- @fontsource/gowun-batang@4.5.2
- @fontsource/gowun-dodum@4.5.2
- @fontsource/hachi-maru-pop@4.5.2
- @fontsource/hahmlet@4.5.2
- @fontsource/hina-mincho@4.5.2
- @fontsource/ibm-plex-sans-kr@4.5.2
- @fontsource/kaisei-decol@4.5.2
- @fontsource/kaisei-harunoumi@4.5.2
- @fontsource/kaisei-opti@4.5.2
- @fontsource/kaisei-tokumin@4.5.2
- @fontsource/kiwi-maru@4.5.3
- @fontsource/klee-one@4.5.2
- @fontsource/new-tegomin@4.5.1
- @fontsource/noto-sans-hk@4.5.2
- @fontsource/noto-sans-jp@4.5.2
- @fontsource/noto-sans-kr@4.5.2
- @fontsource/noto-sans-sc@4.5.2
- @fontsource/noto-sans-tc@4.5.2
- @fontsource/noto-serif-jp@4.5.2
- @fontsource/noto-serif-kr@4.5.2
- @fontsource/noto-serif-sc@4.5.2
- @fontsource/noto-serif-tc@4.5.2
- @fontsource/otomanopee-one@4.5.1
- @fontsource/palette-mosaic@4.5.2
- @fontsource/rampart-one@4.5.2
- @fontsource/shippori-mincho-b1@4.5.1
- @fontsource/shippori-mincho@4.5.1
- @fontsource/stick@4.5.2
- @fontsource/train-one@4.5.2
- @fontsource/yomogi@4.5.2
- @fontsource/yusei-magic@4.5.2
```

All affected fonts have been updated with fixes.

**Comment by iraritchiemeek** [comment]
Getting this same error for @fontsource/zen-kaku-gothic-new and @fontsource/zen-kaku-gothic-antique

**Comment by ayuhito** [comment]
@iraritchiemeek, thanks for the notice. I think I know why this is happening. The upstream parser we use will skip scraping Google's APIs if it determines no updates has been pushed to the version of the font - helps build times immensely else we will be making tens of thousands of unnecessary calls to Google's API.

However, in this specific case, some fonts may not have been updated at all to remove the messed up download metadata we had since the parser does see that the font version from Google does match what Fontsource has.

I'll look into adding a force flag to [fontsource/google-font-metadata](https://github.com/fontsource/google-font-metadata) that skips checking which can then be used on this repo for clearing out similar metadata issues like this in the future.

**Comment by ayuhito** [comment]
```
- @fontsource/zen-antique-soft@4.5.1
- @fontsource/zen-antique@4.5.1
- @fontsource/zen-kaku-gothic-antique@4.5.1
- @fontsource/zen-kaku-gothic-new@4.5.1
- @fontsource/zen-kurenaido@4.5.1
- @fontsource/zen-maru-gothic@4.5.1
- @fontsource/zen-old-mincho@4.5.1
```
The following affected fonts have been updated and fixed.

**Comment by srnIxora** [comment]
Getting the same error for **@fontsource-variable/noto-sans-jp/files/noto-sans-jp-japanese-wght-normal.woff2**.

NPM Package info: 
 **"@fontsource-variable/noto-sans-jp": "^5.0.19",**

**Comment by ayuhito** [comment]
That file does not exist. See the [CSS file](https://cdn.jsdelivr.net/npm/@fontsource-variable/noto-sans-jp@5.0.19/wght.css) for reference.

**Comment by srnIxora** [comment]
Thanks. May be documentation need to be updated. Please see the image.
![image](https://github.com/fontsource/fontsource/assets/119561529/1e8263a9-c5e7-4904-a208-72aabdac39d2)
