### ISSUE TITLE
Open Sans: Mixin "fontFaceCustom" uses "Open SansVariable" as $fontName

### ISSUE THREAD

**Issue by codegain** [DecliningLotus/fontsource#356]
**Describe the bug**
If you include the file https://github.com/fontsource/fontsource/blob/main/packages/open-sans/scss/mixins.scss and use the "fontFaceCustom" method without providing a `$fontName`, the resulting CSS will output `Open SansVariable` as `font-family`.

**To Reproduce**

1. Include the file https://github.com/fontsource/fontsource/blob/main/packages/open-sans/scss/mixins.scss in your own .scss file
2. Use `fontFaceCustom` without providing `$fontName`
3. Compile to CSS
4. `font-family` is now `Open SansVariable`

**Expected behavior**
`font-family` should be `Open Sans`.

**Additional context**
This may be intruduced by https://github.com/fontsource/fontsource/commit/59d890b826e48c1a52d39032813facc75e37d8f0.

**Comment by ayuhito** [comment]
I think until google/fonts#3870 is resolved, I can't really look into this since too many variables are astray.

**Comment by thasmo** [comment]
This also happens when using the default `fontFace` mixin from the same file. I've noticed that various variables in `scss/mixins` are declared multiple times in multiple locations, thus overwriting themselves, I guess. This rather feels like the mixins are not working with Sass modules - I'm not sure this is directly related to the Google API.

**Comment by thasmo** [comment]
I think this may rather be a duplicate of #153 and not a Google Fonts API issue.

**Comment by ayuhito** [comment]
I honestly think the whole SASS implementation with Fontsource needs to be redone and reviewed, especially after multiple iterations trying to add new features and then ending up creating bugs like #153 from poor planning and research from me. 

It'll be a breaking change thing, but I'd honestly want someone who uses SASS regularly and understands it properly to help with the implementation. 

It should be pretty simple for someone not familiar with Fontsource's source code to work on since it's editing templates.

**Comment by thasmo** [comment]
> It should be pretty simple for someone not familiar with Fontsource's source code to work on since it's editing templates.

A quick `git clone` left me to realize it may not be that quick after all. 😅

**Comment by ayuhito** [comment]
> A quick `git clone` left me to realize it may not be that quick after all. 😅

Honestly the biggest hurdle of getting new contributors is that first step 😭

**Comment by thasmo** [comment]
> Honestly the biggest hurdle of getting new contributors is that first step 😭

You mean all other hurdles are smaller? 😄

I thought I give it a shot right now; at the same time realizing that using variable fonts and Sass modules is something I have sat out successfully to this day. 😅

**Comment by thasmo** [comment]
Had a "quick" look at it and imo the issue is "resolvable" (for Sass module usage) only by renaming the duplicated variable names in the `scss` file. This would fix the usage via `@use` (Sass modules) but it would probably break usage via `@import`, because variable names for certain mixins change; e.g. a "fix" would be to rename `$fontName` to `$variableFontName` for the `fontFaceVariable` and `fontFaceVariableCustom` mixins, but that means when using `@import` it's not possible to define the "default" variable via `$fontName` beforehand anymore, `$variableFontName` must be used instead.

This "fix" won't resolve the issue in #153 tho. (Which is an issue when using `@import`.)

I feel like a single mixin for all the current use cases (`@use`, `@import`, variable fonts, custom declarations, etc.) could be possible and if this new mixin is provided in a separate file, it wouldn't be a breaking change but rather a new feature.

**Comment by ayuhito** [comment]
> I feel like a single mixin for all the current use cases (`@use`, `@import`, variable fonts, custom declarations, etc.) could be possible and if this new mixin is provided in a separate file, it wouldn't be a breaking change but rather a new feature.

Ideally, it would serve as a replacement for the existing mixins, correct? Instead of breaking, we could just deprecate and recommend this one and then phase out the old ones which are a bit messy next major update.

A possible concern I have with an "all in one" solution is complexity since there's loads of different variables at play, but maybe it's not too bad. Thoughts?

**Comment by thasmo** [comment]
@DecliningLotus, had some more time to dig a bit deeper into this.

What do you think of this, as a first static draft (using Open Sans as the example font)?
https://www.sassmeister.com/gist/9f484e76c9cd1e3d5b54d9bea9b6a472

This does not include some functionality of the current "custom" mixins and it does not solve #153 either. I do have some more thoughts and ideas about certain things related to this initial draft, but I'd love to first hear about your thoughts and opinion on it.

Thanks for your time! 👍

**Comment by ayuhito** [comment]
@thasmo, I will admit, I am unsure to provide full feedback as my understanding of Sass remains at a basic level and is not very up to date. I do have a concern regarding options for people dependent on older versions of Sass that do not have `@use` and are dependent on `@import`. Although for legacy users like that, maybe we could just give them a less versatile but at least compatible mixin dedicated for them.

Perhaps @cbirdsong and @davidjb could drop in their thoughts regarding this instead, as they were largely involved with pushing ideas for Fontsource's Sass implementation. It would be great if others also want to drop their own thoughts here.

**Comment by ayuhito** [comment]
@thasmo, do you want to create a separate issue proposing your new draft? I feel this diverges from the original issue too much.

**Comment by cbirdsong** [comment]
An `@use`-based module is definitely the long-term answer, but I haven't written or even used enough modules to speak to how one should be structured.

As far as a short-term fix goes, maybe you could split the existing file into multiple partials that could also be imported independently. Possibly something like this?

`mixins-standard.scss`, which would basically be the whole file for non-variable fonts:
```scss
$fontName: "Open Sans";
$fontId: "open-sans";
$style: normal;
$display: swap;
$weight: 400;
$fontDir: "~@fontsource/#{$fontId}/files";
// also $unicodeMap and any other variables

// the non-variable font mixins
```

`mixins-variable.scss`, which would include all the necessary variables, not just the ones from the variable font section of the current file:
```scss
$fontName: "Open SansVariable";
$fontId: "open-sans";
$weight: 300 800;
$type: "wghtOnly";
$stretch: 75% 100%;
$style: normal;
$display: swap;
$fontDir: "~@fontsource/#{$fontId}/files";
// also $unicodeMap and any other variables

// the variable font mixins
```

`mixins.scss`, which would only exist for backwards compatibility:
```scss
@import "mixins-standard";
@import "mixins-variable";
```

When the newer Sass module mixins are ready they can then be dropped into `/scss/` in as `modules.scss`, `module-<variant>.scss` or maybe even `fontsource.scss`.

Things I'm not sure about:

- Would it be best to not include `mixins-variable` in `mixins.scss` since the variable naming it has essentially broken the standard Sass mixins? 
- Could/should these have different file names to it more clear these are the legacy `@import`-friendly files/mixins?

**Comment by thasmo** [comment]
> @thasmo, do you want to create a separate issue proposing your new draft? I feel this diverges from the original issue too much.

> The Sass team discourages the continued use of the @import rule. Sass will gradually phase it out over the next few years, and eventually remove it from the language entirely. Prefer the @use rule instead. 

As I believe that the current issues are not solvable in a decent way when using the mixins via `@import`, I would be willing to suggest a backwards-incompatible but proper and flexible solution for Sass when used via `@use` aka `Sass Modules`.

@DecliningLotus, is that something you deem worthwhile for the fontsource project? If so, I'd create a new issue/discussion/PR as soon as I have some time.

**Comment by ayuhito** [comment]
@thasmo, I'm happy with that. Thanks for your time. :) 

I think we could later on just create a dedicated mixin just for `@import` that may lack many features, but at least lets you import fonts in via Sass and change basic things. Too many legacy projects for us to not ignore. Honestly, the Sass code before we introduced #129 would be appropriate for that. Bug-free and not complex at all.

**Comment by thasmo** [comment]
@DecliningLotus, at the moment `fontsource` packages feature font files for `all` variable font variations and a `wghtOnly` variation. Is there a reason for not providing a variation per axis? I guess it doesn't make sense to generate all possible combinations of available axes, but one file per axis would work. Is there a technical limitation which hinders the generation of a font file per axis?

**Comment by ayuhito** [comment]
It is possible for us to generate font files in any combination of axis. It's a matter of whether we are generating too many unnecessary files per variable font. I don't know how much demand is there for that.

Also please do make a separate issue for ideas like this. It makes it easier to document and refer to in the future when similar questions are asked :)

**Comment by ayuhito** [comment]
We've rewritten the Sass integration entirely for [v5](https://fontsource.org/docs/getting-started/migrate-v5) 🎉 Please let us know if you run into any issues!
