### ISSUE TITLE
Material Icons Rounded rename to Round

### ISSUE THREAD

**Issue by ivanshilo** [DecliningLotus/fontsource#363]
**Describe the bug**
Updated google's css class name is .material-icons-round, you package call it .material-icons-round**ed**. This makes your font to fail on projects that use google's naming.

**Expected behavior**
I want to be able to remove only this reference from a web-page "https://fonts.googleapis.com/css2?family=Material+Icons+Round" and your font should work correctly as a replacer.

**Comment by ayuhito** [comment]
I can't necessarily change it now due to it being a breaking change. However, we could just append a duplicate of the same class with the "correct" CSS class name. 

We can update the relevant documentation and deprecate it for a Fontsource v5 release (which there are no plans for). It's a relatively simple change and can be done by anyone in the templates folder.

**Comment by ayuhito** [comment]
Changed in [v5](https://fontsource.org/docs/getting-started/migrate-v5) 🎉 We no longer export the material icons class and leave that to the user's responsibility.
