### ISSUE TITLE
Font Request: Daniel

### ISSUE THREAD

**Issue by pgnd** [DecliningLotus/fontsource#412]
ORIGINAL AUTHOR SITE
	https://goodreasonblog.com/fontery/

FREE DL
	wget -k "http://danielmidgley.com/fonts/danielfont.zip"

LICENSE
	unzip danielfont.zip
	open "danielfont/Font license - Daniel.pdf"

		--> ‘Daniel’ by Daniel Midgley is licensed under a Creative Commons
		     Attribution-NoDerivs 3.0 Unported License.

ADD'L DOWNLOAD SITE
	https://www.fontsquirrel.com/fonts/daniel

FREE DL
	wget -k "https://www.fontsquirrel.com/fonts/download/daniel" -O daniel.zip

LICENSE
	unzip danielfont.zip
	open "Daniel Midgley.txt"

		--> It’s free for you to use for any purpose, commercial or not.

&

	https://www.fontsquirrel.com/license/daniel

		--> It’s free for you to use for any purpose, commercial or not.

**Comment by ayuhito** [comment]
@pgnd, "You can share this font with anyone, as long as this notice is included.". 

I can't necessarily comply since this isn't a proper license like OFL which is very clear unlike this. I can't enforce obscure licenses like this to all the downstream users.

It's possible you can contact the author to repackage the font under OFL, otherwise I can't really accept this request.
