### ISSUE TITLE
Inter - Capital 'A' not showing correctly

### ISSUE THREAD

**Issue by tayloraucoin** [DecliningLotus/fontsource#417]
Duplicate of `Glitch with Exo 2 uppercase A, B, D, Å, Ä letters since version 4.4.0+, works in 4.3.0` but for `Inter` font: 
https://github.com/fontsource/fontsource/issues/243

`Inter` is mentioned in the comments there but it is never addressed 

Related to: https://github.com/google/fonts/issues/2602 

Tried importing `"@fontsource/inter/variable.css"` and `"@fontsource/inter/variable-full.css"` without any behaviour change 

Latest version `"@fontsource/inter": "^4.5.1"`

**Comment by AlexanderZeilmann** [comment]
[Jost](https://fontsource.org/fonts/jost) is another font that has this problem:

![Bildschirmfoto 2022-01-31 um 15 28 43](https://user-images.githubusercontent.com/901391/151811608-019b9a2b-b45d-4e0e-bba8-f563a33ec58e.png)

At least for Jost, using the variable version of the font fixes the problem.

**Comment by ayuhito** [comment]
I'm pretty unsure since it seems that even the variable font version of Inter is also affected by this. It's something that the upstream issue in Google has to resolve over anything I can do.

**Comment by tayloraucoin** [comment]
@DecliningLotus from what you know, this there anything that I can do as a developer to make sure that my site can render this letter properly? 

How is this such a big global issue that is not being resolved?

Is there somewhere I can monitor the progress on the issue?

**Comment by ayuhito** [comment]
@tayloraucoin, keeping track of google/fonts#2602 is where you can monitor progress on this matter. I believe the true root of the issue is google/woff2#123. 

There is a solution for this. It's embarrassing to say considering Fontsource is all about making self-hosting easy, but the official release for Inter on [rsms/inter](https://github.com/rsms/inter) does not have the bug. You could still self-host if you download it from there. [rsms/inter#302 (comment)](https://github.com/rsms/inter/issues/302#issuecomment-675066630)

This is where it becomes awkward for me. I leave Google Font bugs up to Google to fix themselves and let Fontsource mirror it all. It's not in my interest to add more maintenance to the Fontsource repo by writing new code to support exceptions like these and manually patching fonts due to their sometimes incompatible build process. I just don't have the time to spare for that.
In the end, it's up to Google to sort this out.

**Comment by chrisguttandin** [comment]
I don't know if this helpful in any way but in case of "Montserrat" the problem does not occur when using the font directly from Google. Maybe that means it's already fixed?

I created a StackBlitz project which uses the font from Google Font.

https://web-platform-8h8bxp.stackblitz.io
https://stackblitz.com/edit/web-platform-8h8bxp

And another one which uses the font from the fontsource package. (I had to create an Angular project to be able to include the files from the `node_modules` directory.)

https://angular-ivy-urpsfp.stackblitz.io
https://stackblitz.com/edit/angular-ivy-urpsfp

**Comment by ayuhito** [comment]
@chrisguttandin, Google does two things to my knowledge, I _think_. 

- If your browser is modern enough, it will serve you the variable variant of the font which doesn't have the issue present even in Fontsource (except Inter oops). 
- Otherwise, Google serves the much larger WOFF file to specific Mac users, because the issue derives from the WOFF2 file format itself. Since Google can dynamically serve different CSS depending on the user-agent of the browser, they can "fix" or should I say hide most of the problem for those affected Mac users until a proper solution is figured out.

**Comment by chrisguttandin** [comment]
Thanks for the explanation. I can confirm that at least for me https://fonts.googleapis.com/css2?display=swap&amp;family=Montserrat redirects to https://fonts.gstatic.com/s/montserrat/v23/JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCtr6Hw5aXx-p7K4KLg.woff right now.
