### ISSUE TITLE
Imports an non-existing font nobody asked it to.

### ISSUE THREAD

**Issue by ghost** [DecliningLotus/fontsource#442]
**Describe the bug**
Using fontsource in a svelte project results in a 404 error because it's importing two font variants nobody asked:

**To Reproduce**

In app.js
```js
import '@fontsource/pacifico/400.css';
```

When used in a component
```css
        font-family: 'Pacifico', cursive;
        font-weight: 400;
```

The browser console logs:
```
404 ─ 0.23ms ─ /build/files/pacifico-latin-400-normal.woff2
404 ─ 0.19ms ─ /build/files/pacifico-all-400-normal.woff
```

**Expected behavior**
Fontsource imports the font it was asked to.

**Screenshots**
I don't know much about fonts but this is definetly **NOT** Pacifico font.
![fuckingnodeanditsfuckingtools](https://user-images.githubusercontent.com/24773698/154862400-f90650ef-3fb9-40f5-ae9b-70a099e68ba0.png)

**Additional context**
I don't know what might be wrong I tried different things:

- Same import route in both `app.js` and component
- Import only in component
- Import only in app.js
- Full path import

**Comment by ayuhito** [comment]
Those are the intended font files to be imported. The issue is the 404 error indicating something isn't configured properly and the font files are not being copied over to your build directory?

I don't know much about Svelte to offer assistance on it, although I've seen lots of examples online that work and perhaps you could reference that. The package itself is fine.

I've made #443 in hopes of formalising proper documentation to import Fontsource using Svelte.

**Comment by ghost** [comment]
Ideally no package config should be done. Global css imports can be done in the main `app.js` file. Idk why is it sesrching for the incorrect files :c

I also tried building the project but nope, nothing changed as well. I couldn't find any svelte examples working, few svelte kit ones but not the same :(
