### ISSUE TITLE
New repo fonts not yet available on npm

### ISSUE THREAD

**Issue by elitenoire** [DecliningLotus/fontsource#513]
I noticed that the new google fonts eg. Gantari is not available on npm or on fontsource.org font preview even though it has been added to the repo.

**Comment by ayuhito** [comment]
We've had to pause automatic builds for the moment. Google introduced a font with no variable font wght axis for the first time, and so builds are crashing since we incorrectly assumed that wght must exist as a default. 

They also delisted fonts mid build, so our metadata generator doesn’t have the font file links, but we have the fonts marked to publish in our publisher. Super rare case.

I'll be able to ship a couple fixes soon once I free up a little bit.
