### ISSUE TITLE
Why does Noto Color Emoji CSS/SCSS contain a class .noto-color-emoji?

### ISSUE THREAD

**Issue by CxRes** [DecliningLotus/fontsource#532]
Like the question say, I am unable to understand why this class `.noto-color-emoji` has been defined? Should this not be in user land? At the very least in another file? This is inconsistent with all the other fonts on FontSource (at least those I have used)!

I find that it unnecessarily pollutes my font declarations, and makes automated optimization difficult. Unless there is some reason that I am missing, this class probably need to be removed.

**Comment by ayuhito** [comment]
It's definitely not intended. We added a generator for Material Icons a long long time ago since it needed that custom class, but it seems to have carried over to all packages that are marked as icons.

It might make sense to remove the custom class entirely to clean up our code and instead mark Material Icons specifically with a documentation note to add the class themselves. I agree that it should be a user land addition.

We can make this a breaking change for v5 if that works.

**Comment by CxRes** [comment]
> We can make this a breaking change for v5 if that works.

I am already grateful that you provide this service. While I would like a fix asap, I'll leave it to your best judgement as to how you provide it. I can work around it by manually adding the Sass code for now, though it is ugly.

**Comment by ayuhito** [comment]
I'm happy to accept a quick PR for this if it leaves the same behaviour for all Material Icon packages though. It's not breaking change for other icon packages.

**Comment by ayuhito** [comment]
https://github.com/fontsource/fontsource/blob/main/scripts/generic/generic-packager.ts#L122

Only this if statement needs to be changed for reference.

**Comment by CxRes** [comment]
Now that you point it out, I am reluctant to PR precisely because I am not sure how this class might be depended upon by other users. It is probably better left as a semver breaking change!

**Comment by ayuhito** [comment]
This was closed way back in #590.
