### ISSUE TITLE
Hello! Suggest to add ligatures font type

### ISSUE THREAD

**Issue by zhouxinghong** [DecliningLotus/fontsource#628]
### Describe the feature you'd like to request

Hello! Suggest to add ligatures font type to doppio-one font
![2023-01-21_071001](https://user-images.githubusercontent.com/54253524/213821604-289de38d-d134-4981-860c-cfc2509f0e2c.png)

**Comment by ayuhito** [comment]
Hiya, this repository mirrors Google Fonts who don't have ligatures enabled. A large part of that is to reduce file sizes since these are web-focused fonts. We don't plan on adding support for this. Thanks!

**Comment by zhouxinghong** [comment]
You can actually distribute two versions, one dedicated to the web and one for writing code. That way it won't affect web fonts. . .

**Comment by ayuhito** [comment]
The issue isn’t distribution (although it would double the number of packages we push to NPM to around 3000 packages - might be problematic), but where we can get those font files with ligatures and everything else. Since the Google Fonts repository is optimised for the web, we only have web-friendly fonts as an available source. 

Manually finding and maintaining non-web friendly fonts is out of scope for this project since that would require an immense amount of work and time that I don’t have.
