### ISSUE TITLE
Font Request: IBM Plex Sans Variable

### ISSUE THREAD

**Issue by mdaverde** [DecliningLotus/fontsource#665]
### Font Name

IBM Plex Sans Variable

### Link to font source

https://github.com/IBM/plex/tree/master/IBM-Plex-Sans-Variable

### Link to font license

https://github.com/IBM/plex/blob/master/LICENSE.txt

### Additional context

Thank you!

**Comment by ayuhito** [comment]
If a font already exists upstream at Google, unfortunately, we cannot add it due to future possible conflicts. I suggest following: https://github.com/google/fonts/issues/2407 

Upon its resolution, Fontsource will automatically get the update.

**Comment by zphrs** [comment]
It seems https://github.com/google/fonts/issues/2407 is now resolved as of last month. Any theory as to why Fontsource doesn't have it yet?

**Comment by ayuhito** [comment]
Hi! Sorry, currently automated builds that mirror Google Fonts is disabled while I experiment and test a new `v5.2.0` release in the main [font-files](https://github.com/fontsource/font-files) repository. It's been taking me some time since I'm very busy with other commitments, but I'll see if I can get that sorted sometime soon so we eventually re-enable automated builds.

Also generally it takes a couple weeks after a PR merges in google/fonts to get to us since GF keeps fonts in a sandbox environment for a while before moving to production. It did get moved to production 3 days ago though 👀

**Comment by zphrs** [comment]
Awesome! Thank you so much!

**Comment by zphrs** [comment]
Can I open up a PR for IBM Plex specifically on the main repo?

**Comment by ayuhito** [comment]
To be more specific, we can't release any new packages as those experimental changes I'm testing would get released globally otherwise. A PR won't be usable 😅

**Comment by zphrs** [comment]
Ah, understood. I'll just download the fonts locally then for now. Thank you for all the work you do on the project! It's very cool.
