### ISSUE TITLE
Poppins truetype font file can't work with font-feature-settings

### ISSUE THREAD

**Issue by catiex** [DecliningLotus/fontsource#771]
### Describe the bug

Fontsource poppins truetype font file can't work with font-feature-settings as [Google font](https://fonts.google.com/specimen/Poppins).

### Steps to Reproduce

1. Download Poppins font from [fontsource](https://fontsource.org/fonts/poppins)
2. Unzip the above font file and install `poppins-latin-400-normal.ttf` from `poppins/ttf`
3. Open any small projects showing lower case `a` and use Poppins from locally-installed font.
4. Enable `font-feature-settings: "ss02";` for Poppins font-weight 400.
5. Verify lower case `a` not being updated to double storey.
<img width="818" alt="Screenshot 2023-06-30 at 1 28 23 PM" src="https://github.com/fontsource/fontsource/assets/118233283/e7617bbf-b3cb-436a-86bd-df7642121787">

### Expected behavior

After enabling `(font-feature-settings: "ss02";)` for double-storey lower case a with manually installed Google Poppins truetype font file, lower case `a` shows correctly.

<img width="853" alt="Screenshot 2023-06-30 at 1 39 16 PM" src="https://github.com/fontsource/fontsource/assets/118233283/e898df96-55d9-4c11-b9eb-4566491ee551">

**Comment by ayuhito** [comment]
We actually convert the `woff2` variant of the Google source to `ttf` which doesn't contain any `font-feature-settings` options. Ideally we should use the original [`ttf` files](https://raw.githubusercontent.com/fontsource/google-font-metadata/main/data/google-fonts-v2.json) provided by Google and the fallback to the conversion method when dealing with non-Google fonts.

Although if the `ttf` variants don't support `font-feature-settings` since Google may have stripped those out for size optimisations, supporting this feature would be out of scope.

**Comment by catiex** [comment]
> We actually convert the `woff2` variant of the Google source to `ttf` which doesn't contain any `font-feature-settings` options. Ideally we should use the original [`ttf` files](https://raw.githubusercontent.com/fontsource/google-font-metadata/main/data/google-fonts-v2.json) provided by Google and the fallback to the conversion method when dealing with non-Google fonts.
> 
> Although if the `ttf` variants don't support `font-feature-settings` since Google may have stripped those out for size optimisations, supporting this feature would be out of scope.

Hey Ayu, thank you for your reply. I understand Google fonts CDN doesn't support truetype font files from their API for size optimizations, I am not sure if fontsource is considering the same in the future?

**Comment by ayuhito** [comment]
> Hey Ayu, thank you for your reply. I understand Google fonts CDN doesn't support truetype font files from their API for size optimizations, I am not sure if fontsource is considering the same in the future?

This isn't in this project's scope since we only aim to replicate Google Fonts with optimised fonts for the web. It would be too labour-intensive for us to manually support fonts compared to simply mirroring Google Fonts.

If you need explicit support for this, we can only recommend you download from the source itself. Thanks!

**Comment by ayuhito** [comment]
After a little bit more thought on this, it might make sense to expand the scope of the project to include this. #39 would be the relevant issue to discuss this.
