### ISSUE TITLE
Victor Mono: no preview + application error

### ISSUE THREAD

**Issue by rubjo** [DecliningLotus/fontsource#799]
### Describe the bug

Font previews don't load, and doing this:
1. https://fontsource.org/fonts/victor-mono
2. Click download
3. Click browser back button

...produced this screen:
<img width="733" alt="SCR-20230911-hrak" src="https://github.com/fontsource/fontsource/assets/42270947/140a4228-58d7-423b-b56e-cc1f5f0764cb">

### Steps to Reproduce

1. Go to https://fontsource.org/fonts/victor-mono

**Comment by ayuhito** [comment]
It probably has something to do with how Victor Mono switched from a user-submitted font to a Google font.

#786 should be the first step in fixing that since it seems API-related. The preview logic is very flaky at the moment and I eventually want to replace the generated CSS with an official CSS API which should be much faster and reliable.

**Comment by ayuhito** [comment]
Hopefully closed in #857. Please let me know if the problem persists.
