### ISSUE TITLE
API endpoints not working with error code 522

### ISSUE THREAD

**Issue by AlexTMjugador** [DecliningLotus/fontsource#832]
### Describe the bug

In similar circumstances to https://github.com/fontsource/fontsource/issues/724, fetching at least some fonts (e.g., https://api.fontsource.org/v1/fonts/exo-2/latin-400-normal.ttf) fails with an HTTP 522 status code with no description or body.

### Steps to Reproduce

1. Run `wget https://api.fontsource.org/v1/fonts/exo-2/latin-400-normal.ttf`.
2. Watch it fail as described.

### Expected behavior

Downloading fonts from the API endpoint works.

### Additional context

This has been happening somewhat reliably since at least September 19th, 12:32 UTC. My initial suspicion is that [a recent change](https://github.com/fontsource/fontsource/compare/a5578da58241ca1ad03c714b9541e904126dada6...main) caused this.

**Comment by ayuhito** [comment]
I'm currently debugging this and my initial idea is that it could be a caching bug. It's a bit hard to determine what is causing this though since it works perfectly fine in a local environment. Will follow up when I have more information 👍

**Comment by ayuhito** [comment]
@AlexTMjugador, can you verify if the things are working on your end now? If so, I can make a PR with the fix. 

Instead of trying to proxy content through the worker, I used a 302 redirect which should effectively lead to the same result but _might_ be breaking in certain circumstances. This was what I originally intended to do once we have our jsDelivr CDN proxy available anyways, but for now we'll just be hitting our origin workers instead.

I'll keep this issue open for a while just in case other users experiences problems with the change.

**Comment by AlexTMjugador** [comment]
It works fine for me both on my workstation and on CI workflow runners, thank you very much! :heart:
