### ISSUE TITLE
Website is missing `variable` tag, install instructions and example for `Roboto Condensed`

### ISSUE THREAD

**Issue by loky-lp** [DecliningLotus/fontsource#895]
### Describe the bug

The Fontsource website list only the `300`, `400` and `700` weight variants for `Roboto Condensed` even if the `@fontsource-variable/roboto-condensed` exists and works correctly

Google provides both the standard variants, from `100` to `900`, and the variable one [here](https://fonts.google.com/specimen/Roboto+Condensed)

### Steps to Reproduce

N/A

### Version

N/A

### OS

N/A

### Browser

N/A

**Comment by ayuhito** [comment]
This should now be resolved with the improved cache invalidation from #935. Updates to metadata should be a lot more frequent.

**Comment by mattaw** [comment]
At the moment, after clearing cookies, cache and disabling all adblockers I get this on Chromium:
![image](https://github.com/fontsource/fontsource/assets/4684331/01017f0c-207e-4ba5-a032-5a5091e57c91)

My console log is attached:
[fontsource.org-1707926537039.log](https://github.com/fontsource/fontsource/files/14283261/fontsource.org-1707926537039.log)

[Silly: http://thecodelesscode.com/case/220?topic=cache+invalidation - the two hard things, you only need to remember that the first hard thing is called “cache invalidation”]

**Comment by ayuhito** [comment]
😅 Well, seems like our NPM version API (undocumented) is out of sync and isn't reporting the variable versions. 

I think that was the only API I wasn't able to migrate to the new schema properly (#935) since it is difficult to aggregate all known NPM versions into a single KV object, thus... its cache is not invalidated properly unlike the rest of the metadata.
