### ISSUE TITLE
Fonts become missing

### ISSUE THREAD

**Issue by uuf6429** [DecliningLotus/fontsource#916]
### Describe the bug

From time to time, fonts that used to work are becoming missing/broken.

This is extremely strange and frustrating for a CDN - it is expected to have old (static) assets, but not "broken links".

Yesterday we had a similar situation with Roboto Slab, then suddenly the fonts became available again.

Today I noticed one missing font that is still missing, even though it is referenced from the fontsource site (see repro below).

### Steps to Reproduce

1. Go to https://fontsource.org/fonts/lobster/cdn
2. click the "latin-ext" subset
3. visit the woff2 link in the generated source (under "Copy CSS") - it is as of now broken:
    https://cdn.jsdelivr.net/fontsource/fonts/lobster@latest/latin-ext-400-normal.woff2
    ```json
    {
        "status": 404,
        "error": "Not Found. File does not exist."
    }
    ```

### Expected behavior

> This is extremely strange and frustrating for CDN - it is expected to have old/bad static assets, but not "broken links".

### Version

n/a

### OS

osx

### Browser

chrome

**Comment by ayuhito** [comment]
This is a valid concern and I agree with you. Something is clearly not resolving properly (probably to do with the `@latest` tag) when the cache expires which leads to this occurring.

Is this something that you have been experiencing only recently or something that has been happening for a while? I'm wondering if recent API changes have affected it or it has been a bug since the CDN's inception.

I'll also probably switch default links on the CDN page to not point to `@latest` and instead point to the latest actual version which makes the caches immutable. We can then offer a version list to make `@latest` opt-in.

**Comment by ayuhito** [comment]
#918 should hopefully address this as it seems like the only related thing that could throw that error. However, if you encounter this again, please don't hesitate to reopen this issue.

**Comment by uuf6429** [comment]
Hey, thanks a lot for the quick response and solution!

On a sidenote, I now realise that the safer option for us is to actually not use `@latest`, because then it should be practically guaranteed that the specific version we picked must exist.
