### ISSUE TITLE
`@fontsource/open-sans` updates cause a lot of churn

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [DecliningLotus/fontsource#948]
### Describe the bug

Recent versions of `@fontsource/open-sans` seem to "toggle" between adding a bunch of `open-sans-math-` and `open-sans-symbols-` files and then removing them again.

At least some of these updates seem entirely useless: The CSS and font files in version `5.0.26` appear to be identical to the files in version `5.0.24`! Also if [Google's repo](https://github.com/googlefonts/opensans) is anything to go by, there haven't been any actual updates in 4 months.

I don't know if this is coming from something on Google's end or if it's some sort of issue with automation in this repo, but it would be great if it could be fixed.

### Steps to Reproduce

1. Check the font files in `5.0.24` against those in `5.0.25` and note that a lot of files were modified and a bunch of files were added.
2. Check the font files in `5.0.25` against those in `5.0.26` and note that a lot of files were modified and a bunch of files were deleted.
3. Check the font files in `5.0.24` against those in `5.0.26` and note that there are no changes.

### Expected behavior

There shouldn't be any updates unless something actually changed.

### Additional context

We also use `@fontsource/biryani` and `@fontsource/roboto`, but those don't seem to have the same issue.

**Comment by ayuhito** [comment]
Sorry about that! Turns out there was a long standing issue that went unnoticed for practically a year where manually triggering an update used the latest metadata but our cron job used stale metadata. 

The flip flop was the latest going to stale back to latest when I noticed the metadata versions and timestamps going down instead of going up.

I [pushed a fix](https://github.com/fontsource/font-files/commit/4ab3a410bab8bb86ce1062a0e1d9073b75ea9dae) for the cron job last night, so we hopefully shouldn't experience this in the future.

**Comment by ehoogeveen-medweb** [comment]
Wow, what timing! Does that mean the `open-sans-math-` and `open-sans-symbol-` files from version `5.0.27` are (correctly) part of the latest release?

**Comment by ayuhito** [comment]
> Wow, what timing! Does that mean the `open-sans-math-` and `open-sans-symbol-` files from version `5.0.27` are (correctly) part of the latest release?

That is correct. They are part of the latest release and hopefully shouldn't disappear again!
