### ISSUE TITLE
Option to use local() in @font-face

### ISSUE THREAD

**Issue by muuvmuuv** [DecliningLotus/fontsource#974]
### Describe the feature you'd like to request

Some may not need it but for fonts that most users would potentially have installed it might have a benefit of adding an option to use that local font.

### Describe the solution you'd like

A new option that adds `local()` before any font-face source.

**Comment by ayuhito** [comment]
Generally, the usage of `local()` has fallen out of favour as different operating systems will have different versions of a font that has led to unexpected results. For example, ancient Android devices may not render some characters properly due to the font not being updated for a long time (and it will never be fixed), which breaks Fontsource's principle of versioned fonts and determinism.

We do offer escape hatches for users to write their own CSS so people can opt to use `local()` if it makes sense to do so (see [font-display](https://fontsource.org/docs/getting-started/display)) , but I feel it is better for Fontsource not to promote the usage of `local()` in the documentation because I think generally people don't consider the unexpected edge cases, leading to more problems down the line.

**Comment by muuvmuuv** [comment]
Oh ok, thanks for the clarification. Didn't know that these differ as such so heavily. Makes sense it these cases, just had that thought because in our case for our in-house application, our employees would have them installed anyway. Did not thought about cases where they do not update the font for "years".. good point
